/* Real dishes, by cuisine, for the upper adventure levels.

   Asked for "a regional Georgian dish" in a steamed slot with the week's
   tofu and cauliflower, Flash-Lite either tamed it into "spiced cauliflower
   stew" or put a famous name on something that wasn't that dish
   ("Chakhokhbili — stewed cauliflower", "Ambul thiyal" made with paneer).
   Naming the actual dish in code fixes both: the familiarity is decided by
   which list it comes from, and the gloss tells the model what the dish really
   is, so the name and the food match.

   Each entry: [name, gloss, format, tier].
   - format is a FORMATS key (see MiseApp.jsx), so a slot can be matched to a
     dish that really is cooked that way.
   - tier 3 = known: ordered out or heard of, rarely cooked at home.
     tier 4 = regional: most people haven't eaten it.
     tier 5 = deep: defined by a technique or ingredient a curious cook seeks out.
   - The gloss names the main protein and anything a restriction or heat
     ceiling could trip on, because entries are screened against the person's
     restrictions by matching that text.
   No American home-cooking staples (crab cakes, jambalaya, lo mein): the
   judge, rightly, reads those as everyday food, not "ordered it, never cooked it".
   Everything here is a dinner main that can be done on a weeknight (a long
   braise only where a quick version is honest). */
const B = {
  "Italian-American": [
    ["Shrimp fra diavolo", "shrimp in a garlicky chili-tomato sauce over linguine", "noodle", 3],
    ["Chicken scarpariello", "chicken thighs and sausage with vinegar peppers", "braise", 3],
  ],
  "Tex-Mex": [
    ["Migas", "eggs scrambled with crisp tortilla strips, chiles and cheese", "eggs", 3],
  ],
  "Chinese-American": [
    ["Egg foo young", "crisp egg omelets with shrimp and bean sprouts in gravy", "eggs", 3],
  ],
  "Southern Italian": [
    ["Pasta alla Norma", "pasta with fried eggplant, tomato and ricotta salata", "noodle", 3],
    ["Pasta e ceci", "creamy chickpea and pasta soup with rosemary", "soup", 4],
    ["Acqua pazza", "white fish poached in tomato, garlic and white wine", "braise", 4],
    ["Orecchiette con cime di rapa", "orecchiette with broccoli rabe, anchovy and chili", "noodle", 4],
    ["Pasta con le sarde", "Sicilian pasta with sardines, fennel, raisins, pine nuts and saffron", "noodle", 5],
    ["Sfincione", "Sicilian thick pizza with onion, anchovy and breadcrumbs", "bake", 5],
    ["Cianfotta", "Neapolitan stew of eggplant, peppers, potato and basil", "veg", 4],
  ],
  "Northern Italian": [
    ["Risotto alla milanese", "saffron risotto with parmesan", "grain", 3],
    ["Chicken saltimbocca", "chicken cutlets seared with sage and prosciutto", "sear", 3],
    ["Pizzoccheri", "Valtellina buckwheat pasta with cabbage, potato and fontina", "noodle", 5],
    ["Risi e bisi", "Venetian soupy rice with peas and pancetta", "grain", 5],
    ["Bagna cauda", "vegetables dipped in a hot anchovy-garlic bath, with bread and eggs", "veg", 5],
    ["Sarde in saor", "Venetian sweet-sour sardines with onions and raisins", "sear", 5],
  ],
  Sichuan: [
    ["Mapo tofu", "tofu and ground pork in chili-bean sauce with Sichuan pepper", "braise", 3],
    ["Dan dan noodles", "noodles with spicy ground pork, chili oil and sesame", "noodle", 3],
    ["Gan bian si ji dou", "dry-fried green beans with ground pork and preserved mustard greens", "veg", 4],
    ["Hui guo rou", "twice-cooked pork belly with leeks and chili-bean paste", "sear", 4],
    ["Yu xiang qiezi", "fish-fragrant eggplant with pickled chili, garlic and ginger", "veg", 5],
    ["Shui zhu yu", "fish slices poached in chili-oil broth with Sichuan pepper", "soup", 5],
    ["Suan la fen", "sweet-potato glass noodles in hot-sour black vinegar broth with pork", "noodle", 5],
  ],
  Hunan: [
    ["Xiao chao rou", "Hunan farmhouse pork stir-fried with fresh green chilies", "sear", 4],
    ["Hong shao rou, Mao style", "pork belly red-braised with chilies and star anise", "braise", 4],
    ["Duo jiao yu", "fish steamed under chopped salted chilies", "steam", 5],
    ["La jiao chao dan", "eggs stir-fried with charred green chilies", "eggs", 4],
    ["Hunan smoked-pork and leek stir-fry", "smoked bacon with leeks, garlic and fermented black beans", "sear", 4],
  ],
  Cantonese: [
    ["Char siu", "honey-roast pork shoulder with five-spice", "roast", 3],
    ["Wonton noodle soup", "shrimp-pork wontons and egg noodles in clear broth", "soup", 3],
    ["Beef chow fun", "wide rice noodles seared with beef and bean sprouts", "noodle", 3],
    ["Steamed fish with ginger and scallion", "whole or filleted fish steamed, then sizzled with hot oil and soy", "steam", 4],
    ["Steamed spareribs with black bean", "pork ribs steamed with fermented black beans and garlic", "steam", 5],
    ["Bo zai fan", "clay-pot rice with chicken, lap cheong sausage and a crisp crust", "grain", 5],
    ["Shrimp and egg stir-fry", "silky scrambled eggs with shrimp and scallion, Cantonese style", "eggs", 4],
  ],
  Shanghainese: [
    ["Shanghai fried noodles", "thick noodles with pork and bok choy in dark soy", "noodle", 3],
    ["Hong shao rou", "pork belly red-braised in soy, Shaoxing wine and rock sugar", "braise", 4],
    ["Cong you ban mian", "noodles tossed in fried scallion oil and soy", "noodle", 4],
    ["Fan qie chao dan", "tomato and egg stir-fry over rice", "eggs", 4],
    ["Shi zi tou", "lion's head pork meatballs braised with napa cabbage", "braise", 4],
    ["Drunken chicken", "poached chicken steeped cold in Shaoxing wine", "steam", 5],
  ],
  Japanese: [
    ["Chicken katsu", "panko-crusted chicken cutlet with tonkatsu sauce and cabbage", "sear", 3],
    ["Yakisoba", "stir-fried noodles with pork, cabbage and yakisoba sauce", "noodle", 3],
    ["Katsu sando", "pork cutlet sandwich on soft white bread", "handheld", 3],
    ["Japanese curry rice", "mild roux curry with chicken, carrot and potato", "braise", 3],
    ["Oyakodon", "chicken and egg simmered in dashi over rice", "grain", 4],
    ["Okonomiyaki", "savory cabbage pancake with pork, mayo and sauce", "eggs", 4],
    ["Nikujaga", "beef and potatoes simmered in sweet soy dashi", "braise", 4],
    ["Saba shioyaki", "salt-grilled mackerel with grated daikon and rice", "sear", 5],
    ["Takikomi gohan", "rice cooked in dashi with mushrooms, chicken and burdock", "grain", 5],
    ["Chawanmushi", "silky dashi-egg custard with shrimp and mushroom, with rice", "steam", 5],
  ],
  Korean: [
    ["Bibimbap", "rice with seasoned vegetables, beef, fried egg and gochujang", "grain", 3],
    ["Bulgogi", "thin soy-marinated beef seared hot, with lettuce wraps", "sear", 3],
    ["Kimchi fried rice", "rice fried with kimchi and pork, topped with an egg", "grain", 3],
    ["Kimchi jjigae", "kimchi stew with pork and tofu", "soup", 4],
    ["Japchae", "sweet-potato glass noodles with beef and vegetables", "noodle", 4],
    ["Dakgalbi", "gochujang chicken stir-fried with cabbage and rice cakes", "sear", 4],
    ["Haemul pajeon", "crisp scallion pancake with shrimp and squid", "eggs", 4],
    ["Dubu jorim", "tofu braised in soy and chili flakes", "braise", 4],
    ["Bossam", "boiled pork belly wrapped in lettuce with ssamjang and kimchi", "handheld", 5],
    ["Sundubu jjigae", "soft tofu stew with clams, egg and chili", "soup", 5],
  ],
  Vietnamese: [
    ["Banh mi", "baguette with lemongrass pork, pickled carrot and herbs", "handheld", 3],
    ["Goi cuon", "fresh rice-paper rolls with shrimp and herbs", "raw", 3],
    ["Pho ga", "quick chicken pho with charred ginger and star anise", "soup", 3],
    ["Bun cha", "grilled pork patties with rice noodles, herbs and nuoc cham", "noodle", 4],
    ["Bo luc lac", "shaking beef cubes seared with watercress and lime-pepper dip", "sear", 4],
    ["Ga xao sa ot", "lemongrass-chili chicken stir-fry", "sear", 4],
    ["Banh xeo", "crisp turmeric rice crepes with shrimp and pork", "handheld", 5],
    ["Ca kho to", "fish braised in caramel and fish sauce in a clay pot", "braise", 5],
    ["Canh chua", "sour tamarind fish soup with pineapple and okra", "soup", 5],
  ],
  Thai: [
    ["Pad see ew", "wide rice noodles with chicken, Chinese broccoli and dark soy", "noodle", 3],
    ["Pad kra pao", "holy basil pork stir-fry with a crisp fried egg", "sear", 3],
    ["Green curry", "chicken in green curry and coconut milk with Thai eggplant", "braise", 3],
    ["Tom kha gai", "chicken coconut soup with galangal and lime leaf", "soup", 3],
    ["Larb", "minced pork with toasted rice powder, lime and herbs in lettuce cups", "handheld", 4],
    ["Khao man gai", "poached chicken and ginger rice with soybean sauce", "grain", 4],
    ["Khao soi", "curry noodle soup with chicken and crispy noodles", "noodle", 4],
    ["Kai jeow", "puffy crisp Thai omelet over rice with chili sauce", "eggs", 4],
    ["Pla nueng manao", "fish steamed with lime, garlic and chili", "steam", 5],
    ["Gaeng som", "sour orange curry with fish and vegetables", "soup", 5],
  ],
  Malaysian: [
    ["Curry laksa", "coconut curry noodle soup with shrimp, tofu puffs and egg", "noodle", 4],
    ["Nasi lemak", "coconut rice with sambal, fried anchovies, egg and cucumber", "grain", 4],
    ["Beef rendang", "beef simmered down in coconut and spice paste until dry", "braise", 4],
    ["Char kway teow", "flat rice noodles wok-fried with shrimp, egg and bean sprouts", "noodle", 4],
    ["Ikan bakar", "fish grilled in banana leaf with sambal", "sear", 5],
    ["Asam pedas", "sour-spicy tamarind fish stew with okra", "soup", 5],
    ["Telur dadar", "Malay omelet with shallots and chilies over rice", "eggs", 5],
  ],
  Filipino: [
    ["Chicken adobo", "chicken braised in vinegar, soy, garlic and bay", "braise", 3],
    ["Lumpia", "crisp pork and vegetable spring rolls", "handheld", 3],
    ["Pancit bihon", "rice noodles with chicken, cabbage and calamansi", "noodle", 4],
    ["Sinigang", "sour tamarind soup with pork and vegetables", "soup", 4],
    ["Bistek tagalog", "beef with soy-calamansi sauce and onion rings", "sear", 4],
    ["Arroz caldo", "ginger chicken rice porridge with egg and fried garlic", "grain", 4],
    ["Tortang talong", "charred eggplant flattened into an egg omelet", "eggs", 5],
    ["Kinilaw", "fish cured in vinegar and calamansi with ginger and chili", "raw", 5],
    ["Ginataang kalabasa", "squash and shrimp in coconut milk", "veg", 5],
  ],
  Bengali: [
    ["Kathi roll", "Kolkata egg-paratha roll with spiced chicken and onions", "handheld", 4],
    ["Chingri malai curry", "shrimp in coconut milk with garam masala", "braise", 4],
    ["Dimer dalna", "eggs and potatoes in a ginger-cumin curry", "eggs", 4],
    ["Shorshe maach", "fish in mustard-seed paste with green chili and mustard oil", "steam", 5],
    ["Macher jhol", "light fish and potato curry with panch phoron", "soup", 5],
    ["Shukto", "bittersweet vegetable stew with mustard and ginger", "veg", 5],
    ["Cholar dal", "chana dal with coconut and raisins, with rice", "grain", 5],
  ],
  Gujarati: [
    ["Khichdi and kadhi", "rice and moong dal with a yogurt-chickpea-flour kadhi", "grain", 4],
    ["Thepla wraps", "fenugreek flatbreads with spiced potato and yogurt", "handheld", 4],
    ["Dal dhokli", "sweet-sour dal with wheat dumplings simmered in it", "soup", 5],
    ["Sev tameta nu shaak", "sweet-sour tomato curry topped with crisp chickpea-flour sev", "veg", 5],
    ["Ringan no olo", "smoky mashed eggplant with garlic and green onion", "veg", 5],
  ],
  "South Indian": [
    ["Rava dosa", "lacy semolina crepes with potato masala and coconut chutney", "handheld", 4],
    ["Sambar", "lentil and vegetable tamarind stew with rice", "soup", 4],
    ["Chicken chettinad", "chicken in black pepper, fennel and coconut masala", "braise", 4],
    ["Fish moilee", "Kerala fish in coconut milk with turmeric and curry leaves", "braise", 4],
    ["Bisi bele bath", "one-pot rice, lentils and vegetables with tamarind and spice", "grain", 5],
    ["Nadan mutta roast", "Kerala boiled eggs in a dark onion-tomato masala", "eggs", 5],
    ["Avial", "mixed vegetables in coconut and yogurt with curry leaves", "veg", 5],
  ],
  Punjabi: [
    ["Butter chicken", "chicken in a buttery tomato-cream sauce", "braise", 3],
    ["Chana masala", "chickpeas in a tangy onion-tomato masala", "braise", 3],
    ["Palak paneer", "paneer in spiced spinach", "veg", 3],
    ["Rajma chawal", "kidney bean curry with rice", "grain", 4],
    ["Keema matar", "ground lamb with peas and garam masala", "sear", 4],
    ["Amritsari fish", "fish fried in chickpea-flour batter with ajwain", "sear", 5],
  ],
  "Sri Lankan": [
    ["Devilled prawns", "shrimp stir-fried with peppers, onion and chili-tomato", "sear", 4],
    ["Kottu roti", "chopped flatbread stir-fried with egg, chicken and vegetables", "sear", 4],
    ["Parippu", "red lentil coconut dal tempered with curry leaves, with rice", "grain", 4],
    ["Ambul thiyal", "sour fish curry dried down with goraka or tamarind and black pepper", "braise", 5],
    ["Black pork curry", "pork in dark-roasted curry powder with tamarind", "braise", 5],
    ["Beetroot curry", "beets in coconut milk with curry leaves, with rice and an egg", "veg", 5],
  ],
  Persian: [
    ["Joojeh kabab", "saffron-lemon chicken kebabs with rice", "sear", 4],
    ["Kuku sabzi", "herb-packed frittata with walnuts and barberries", "eggs", 4],
    ["Adas polo", "rice with lentils, dates and caramelized onion", "grain", 4],
    ["Mirza ghasemi", "smoky eggplant with garlic, tomato and egg", "veg", 5],
    ["Fesenjan", "chicken in walnut and pomegranate molasses sauce", "braise", 5],
    ["Kashk-e bademjan", "fried eggplant with whey, mint and walnuts", "veg", 5],
    ["Ash reshteh", "herb, bean and noodle soup with kashk and fried mint", "soup", 5],
  ],
  Lebanese: [
    ["Chicken shawarma", "spiced chicken in flatbread with garlic toum and pickles", "handheld", 3],
    ["Shish taouk", "garlic-lemon chicken skewers", "sear", 3],
    ["Mujaddara", "lentils and rice with deeply caramelized onions", "grain", 4],
    ["Fatteh", "chickpeas over toasted pita with garlic yogurt and pine nuts", "bake", 4],
    ["Loubieh bi zeit", "green beans stewed in tomato and olive oil", "veg", 4],
    ["Samkeh harra", "fish baked in a chili, coriander and tahini sauce", "bake", 5],
    ["Kibbeh bil sanieh", "baked layered bulgur and spiced lamb", "bake", 5],
  ],
  Turkish: [
    ["Köfte", "grilled spiced lamb meatballs with flatbread", "sear", 3],
    ["Menemen", "eggs scrambled into peppers and tomato", "eggs", 4],
    ["Lahmacun", "thin flatbread with spiced lamb, rolled with herbs", "bake", 4],
    ["Mercimek çorbası", "red lentil soup with paprika butter", "soup", 4],
    ["Imam bayildi", "eggplant stuffed with onion and tomato, baked in olive oil", "veg", 4],
    ["Çılbır", "poached eggs on garlic yogurt with chili butter", "eggs", 5],
    ["Karnıyarık", "eggplant split and stuffed with spiced ground lamb", "bake", 5],
  ],
  Levantine: [
    ["Falafel", "herby chickpea fritters in pita with tahini", "handheld", 3],
    ["Hummus bil lahme", "warm hummus topped with spiced lamb and pine nuts", "veg", 4],
    ["Msabbaha", "warm whole chickpeas in lemon-garlic tahini", "veg", 4],
    ["Musakhan", "sumac-roast chicken on flatbread with heaps of onion", "roast", 5],
    ["Maqluba", "upside-down rice with eggplant, cauliflower and chicken", "grain", 5],
    ["Kofta bil tahini", "kofta baked with potatoes in tahini sauce", "bake", 5],
  ],
  Georgian: [
    ["Khachapuri adjaruli", "cheese-filled bread boat with an egg baked in", "bake", 4],
    ["Chakhokhbili", "chicken stewed with tomato, onion and lots of herbs", "braise", 4],
    ["Mtsvadi", "pork skewers with onion and sour plum tkemali", "sear", 4],
    ["Lobio", "kidney beans with coriander, walnuts and herbs", "braise", 5],
    ["Shkmeruli", "fried chicken finished in a garlic-milk sauce", "roast", 5],
    ["Chikhirtma", "chicken soup thickened with egg and vinegar", "soup", 5],
    ["Ajapsandali", "eggplant, pepper and tomato stew with basil and coriander", "veg", 5],
  ],
  "Georgian Black Sea": [
    ["Megruli khachapuri", "Mingrelian cheese bread with cheese on top too", "bake", 4],
    ["Kharcho", "beef soup with walnuts, sour plum and khmeli suneli", "soup", 5],
    ["Elarji", "cornmeal cooked with stretchy sulguni cheese, with a walnut sauce", "grain", 5],
    ["Satsivi", "poached chicken in a spiced walnut sauce", "braise", 5],
    ["Kupati", "spiced pork sausages with pomegranate and onions", "sear", 5],
  ],
  Armenian: [
    ["Lule kebab", "ground lamb kebabs in lavash with herbs and onion", "handheld", 4],
    ["Khorovats", "pork skewers with charred peppers and tomatoes", "sear", 4],
    ["Eetch", "bulgur cooked in tomato and peppers with lemon", "grain", 5],
    ["Spas", "warm yogurt soup with wheat and mint", "soup", 5],
    ["Armenian baked manti", "tiny baked beef dumplings in broth with garlic yogurt", "bake", 5],
  ],
  Egyptian: [
    ["Koshari", "lentils, rice and pasta with a vinegar-tomato sauce and fried onions", "grain", 4],
    ["Ful medames", "fava beans with cumin, lemon and olive oil, with eggs", "braise", 4],
    ["Hawawshi", "spiced beef baked inside pita", "handheld", 5],
    ["Ta'ameya", "fava-bean and herb falafel in bread with tahini", "handheld", 5],
    ["Molokhia", "jute-leaf soup with garlic and coriander, with chicken and rice", "soup", 5],
    ["Sayadeya", "fish over cumin rice cooked dark with caramelized onions", "grain", 5],
  ],
  Moroccan: [
    ["Chicken tagine with preserved lemon", "chicken with preserved lemon, olives and ginger", "braise", 3],
    ["Kefta mkaouara", "meatball and egg tagine in spiced tomato", "braise", 4],
    ["Harira", "lentil, chickpea and tomato soup with herbs", "soup", 4],
    ["Zaalouk", "smoky eggplant and tomato with flatbread and eggs", "veg", 4],
    ["Chermoula fish", "fish roasted in a herb-cumin-lemon chermoula with potatoes", "roast", 4],
    ["Couscous aux sept légumes", "couscous with a seven-vegetable broth and chickpeas", "grain", 5],
  ],
  Tunisian: [
    ["Shakshuka", "eggs poached in a peppery tomato sauce", "eggs", 3],
    ["Lablabi", "chickpea soup with harissa, cumin, egg and torn bread", "soup", 5],
    ["Brik", "crisp pastry with egg, tuna and capers", "handheld", 5],
    ["Ojja merguez", "eggs in harissa-tomato sauce with merguez sausage", "eggs", 5],
    ["Tunisian tajine", "baked frittata-like tajine with chicken, cheese and parsley", "bake", 5],
    ["Slata mechouia", "charred pepper and tomato salad with tuna and egg", "veg", 5],
    ["Couscous au poisson", "fish couscous in a spiced tomato broth", "grain", 5],
  ],
  Senegalese: [
    ["Chicken yassa", "chicken with lemon-mustard caramelized onions", "braise", 4],
    ["Mafe", "peanut-tomato stew with chicken", "braise", 4],
    ["Thieboudienne", "fish and broken rice in tomato with a parsley-garlic stuffing", "grain", 5],
    ["Dibi", "grilled lamb with onions and mustard", "sear", 5],
    ["Accara", "black-eyed pea fritters in bread with onion-tomato sauce", "handheld", 5],
  ],
  Nigerian: [
    ["Jollof rice", "smoky tomato-pepper rice with chicken", "grain", 4],
    ["Suya", "beef skewers in peanut-chili yaji spice", "sear", 4],
    ["Efo riro", "spinach stewed in a red pepper base with beef and locust beans", "veg", 5],
    ["Egusi soup", "ground melon-seed soup with greens and beef", "soup", 5],
    ["Moi moi", "steamed black-eyed pea pudding with egg", "steam", 5],
    ["Pepper soup", "fish or chicken pepper soup with calabash nutmeg", "soup", 5],
  ],
  Ethiopian: [
    ["Misir wat", "red lentils in berbere and onion", "braise", 4],
    ["Tibs", "beef sautéed with rosemary, onion and green chili", "sear", 4],
    ["Atakilt wat", "cabbage, carrot and potato with turmeric and ginger", "veg", 4],
    ["Doro wat", "chicken and eggs in berbere-onion stew with spiced butter", "braise", 5],
    ["Shiro", "silky chickpea-flour stew with berbere", "braise", 5],
    ["Gomen", "collards with garlic, ginger and spiced butter, with lentils", "veg", 5],
    ["Firfir", "torn flatbread tossed in a berbere sauce with beef", "sear", 5],
  ],
  "South African": [
    ["Bobotie", "curried ground beef baked under an egg custard", "bake", 4],
    ["Boerewors roll", "coriander sausage in a roll with tomato-onion relish", "handheld", 4],
    ["Chakalaka and pap", "spicy bean and vegetable relish over maize porridge", "veg", 5],
    ["Bunny chow", "Durban curry served in a hollowed loaf", "handheld", 5],
    ["Sosaties", "apricot-curry lamb skewers", "sear", 5],
    ["Cape Malay chicken curry", "chicken curry with cinnamon, cardamom and potatoes", "braise", 4],
  ],
  Oaxacan: [
    ["Entomatadas", "tortillas folded in tomato sauce with chicken and queso fresco", "bake", 4],
    ["Memelas", "thick masa cakes with black beans, salsa and cheese", "handheld", 4],
    ["Tlayuda", "big crisp tortilla with bean paste, quesillo and cabbage", "handheld", 5],
    ["Mole amarillo", "chicken and vegetables in yellow mole thickened with masa", "braise", 5],
    ["Enmoladas", "tortillas in mole negro around shredded chicken", "bake", 5],
    ["Chiles rellenos de picadillo", "roasted poblanos stuffed with spiced pork", "sear", 4],
  ],
  Yucatecan: [
    ["Pollo pibil", "achiote and sour-orange chicken with pickled red onion", "roast", 4],
    ["Huevos motuleños", "fried eggs on tortillas with beans, ham and peas", "eggs", 4],
    ["Sopa de lima", "chicken soup with lime and crisp tortilla strips", "soup", 5],
    ["Poc chuc", "sour-orange pork grilled with charred onion", "sear", 5],
    ["Papadzules", "tortillas with egg in pumpkin-seed sauce", "eggs", 5],
    ["Tikin xic", "achiote fish roasted in banana leaf", "roast", 5],
  ],
  "Northern Mexican": [
    ["Machaca con huevo", "shredded dried beef scrambled with egg and peppers", "eggs", 4],
    ["Frijoles charros", "pinto beans with bacon, chorizo and chiles", "soup", 4],
    ["Caldillo", "beef and potato stew with dried chiles", "soup", 5],
  ],
  "New Mexican": [
    ["Green chile stew", "pork, potatoes and roasted green chiles", "soup", 4],
    ["Stacked red chile enchiladas", "blue-corn tortillas stacked with red chile and a fried egg", "bake", 4],
    ["Calabacitas", "squash and corn with green chile and cheese", "veg", 4],
    ["Carne adovada", "pork in red chile sauce", "braise", 5],
    ["Posole", "hominy soup with pork and red chile", "soup", 4],
  ],
  Peruvian: [
    ["Ceviche", "fish cured in lime with aji, red onion and sweet potato", "raw", 3],
    ["Lomo saltado", "beef, onion and tomato seared with soy, over fries and rice", "sear", 4],
    ["Aji de gallina", "chicken in creamy aji amarillo and walnut sauce", "braise", 4],
    ["Arroz con pollo peruano", "coriander-green rice with chicken", "grain", 4],
    ["Tallarines verdes", "pasta in basil-spinach-queso fresco sauce with steak", "noodle", 5],
    ["Causa", "layered cold potato with aji amarillo and tuna", "veg", 5],
    ["Papa a la huancaína", "potatoes in aji amarillo cheese sauce with eggs", "veg", 5],
  ],
  Brazilian: [
    ["Moqueca", "fish in coconut milk with peppers and dende oil", "braise", 4],
    ["Picanha", "seared beef with farofa and vinaigrette salsa", "sear", 4],
    ["Bobó de camarão", "shrimp in a cassava and coconut purée", "braise", 5],
    ["Arroz carreteiro", "rice with dried beef and sausage", "grain", 5],
    ["Escondidinho", "cassava mash baked over shredded beef", "bake", 5],
    ["Xinxim de galinha", "chicken with peanuts, cashews and dried shrimp", "braise", 5],
  ],
  Argentine: [
    ["Empanadas", "baked beef empanadas with olives and egg", "bake", 3],
    ["Choripán", "chorizo in a roll with chimichurri", "handheld", 4],
    ["Tarta de acelga", "chard and egg pie", "bake", 4],
    ["Carbonada", "beef stew with squash, corn and peaches", "braise", 5],
    ["Humita en olla", "fresh corn stewed with onion, squash and cheese", "veg", 5],
  ],
  Cuban: [
    ["Ropa vieja", "shredded beef in tomato and peppers", "braise", 3],
    ["Picadillo", "ground beef with olives, raisins and tomato", "sear", 4],
    ["Mojo pork", "pork shoulder in sour-orange garlic mojo", "roast", 4],
    ["Vaca frita", "crisp shredded beef with lime and onions", "sear", 5],
    ["Frita cubana", "chorizo-spiced beef burger with shoestring potatoes", "handheld", 5],
    ["Huevos a la cubana", "fried eggs over rice with tomato sauce and plantain", "eggs", 5],
  ],
  "Puerto Rican": [
    ["Arroz con gandules", "rice with pigeon peas, sofrito and pork", "grain", 4],
    ["Pollo guisado", "chicken stewed with sofrito, potatoes and olives", "braise", 4],
    ["Mofongo", "mashed fried plantain with garlic and crisp pork", "veg", 5],
    ["Pastelón", "sweet plantain lasagna with picadillo", "bake", 4],
    ["Jibarito", "steak sandwich with fried plantain for bread", "handheld", 5],
    ["Asopao de pollo", "soupy rice with chicken and sofrito", "soup", 5],
  ],
  Jamaican: [
    ["Jerk chicken", "chicken in an allspice, thyme and chili jerk marinade", "roast", 3],
    ["Brown stew chicken", "chicken browned in sugar and stewed with thyme", "braise", 4],
    ["Jamaican beef patties", "flaky turmeric pastry with spiced beef", "bake", 4],
    ["Escovitch fish", "fried fish under pickled peppers and onion", "sear", 5],
    ["Run down", "mackerel simmered down in coconut milk", "braise", 5],
    ["Ackee and saltfish", "salt cod with ackee, peppers and onion", "sear", 5],
    ["Callaloo with saltfish", "steamed greens with salt cod and thyme", "veg", 5],
  ],
  Basque: [
    ["Piperade", "peppers and tomatoes cooked down with eggs and ham", "eggs", 4],
    ["Pollo a la vasca", "chicken with peppers, tomato and Espelette", "braise", 4],
    ["Marmitako", "tuna and potato stew with peppers", "soup", 5],
    ["Merluza en salsa verde", "hake in a parsley and clam sauce", "braise", 5],
    ["Bacalao al pil-pil", "salt cod in an olive oil and garlic emulsion", "sear", 5],
  ],
  Catalan: [
    ["Botifarra amb mongetes", "pork sausage with white beans and allioli", "sear", 4],
    ["Escalivada", "roasted eggplant, peppers and onion with anchovies and toast", "roast", 4],
    ["Espinacas a la catalana", "spinach with raisins, pine nuts and chickpeas", "veg", 4],
    ["Fideuà", "toasted thin noodles cooked in seafood stock with allioli", "noodle", 5],
    ["Suquet de peix", "fish and potato stew finished with almond picada", "soup", 5],
    ["Arròs negre", "squid-ink rice with squid and allioli", "grain", 5],
  ],
  Provençal: [
    ["Ratatouille", "eggplant, zucchini, pepper and tomato stew with an egg", "veg", 3],
    ["Pan bagnat", "tuna, egg and olive sandwich soaked in olive oil", "handheld", 4],
    ["Pissaladière", "onion tart with anchovies and olives", "bake", 5],
    ["Bourride", "white fish soup thickened with aioli", "soup", 5],
    ["Le grand aïoli", "poached cod, eggs and vegetables with garlic aioli", "veg", 5],
  ],
  Lyonnaise: [
    ["Salade lyonnaise", "frisée with lardons, croutons and a poached egg", "eggs", 4],
    ["Poulet à la crème", "chicken in a mushroom-cream sauce", "braise", 4],
    ["Pommes lyonnaises with sausage", "potatoes and onions crisped with sausage", "sear", 4],
    ["Poulet au vinaigre", "chicken braised in vinegar and tomato", "braise", 5],
    ["Oeufs en meurette", "eggs poached in red-wine sauce with bacon on toast", "eggs", 5],
  ],
  Greek: [
    ["Shrimp saganaki", "shrimp in tomato with feta and ouzo", "braise", 3],
    ["Spanakopita", "spinach and feta in crisp phyllo", "bake", 4],
    ["Gigantes plaki", "giant beans baked in tomato and dill", "bake", 4],
    ["Briam", "roasted vegetables in olive oil and tomato with feta", "roast", 4],
    ["Avgolemono", "chicken, rice and egg-lemon soup", "soup", 4],
    ["Youvetsi", "orzo baked with lamb in tomato and cinnamon", "bake", 5],
    ["Fasolakia", "green beans and potatoes stewed in tomato", "veg", 5],
  ],
  Portuguese: [
    ["Piri-piri chicken", "chicken in a chili, garlic and lemon marinade", "roast", 3],
    ["Caldo verde", "kale, potato and chouriço soup", "soup", 4],
    ["Bifana", "garlic-wine pork cutlet sandwich", "handheld", 4],
    ["Bacalhau à Brás", "salt cod with matchstick potatoes and soft egg", "eggs", 5],
    ["Carne de porco à alentejana", "pork and clams with potatoes and coriander", "braise", 5],
    ["Açorda", "garlic-coriander bread soup with poached eggs", "soup", 5],
    ["Arroz de marisco", "soupy rice with shrimp and clams", "grain", 5],
  ],
  Polish: [
    ["Placki ziemniaczane", "potato pancakes with sour cream and smoked sausage", "sear", 4],
    ["Gołąbki", "cabbage rolls with beef and rice in tomato", "braise", 4],
    ["Żurek", "sour rye soup with sausage and egg", "soup", 5],
    ["Łazanki", "square noodles with sauerkraut, mushrooms and kielbasa", "noodle", 5],
    ["Kopytka", "potato dumplings with brown butter and pork", "noodle", 5],
  ],
  Hungarian: [
    ["Chicken paprikash", "chicken in paprika and sour cream with noodles", "braise", 3],
    ["Goulash", "beef and potato soup with sweet paprika and caraway", "soup", 4],
    ["Lecsó", "peppers and tomato stewed with paprika, sausage and eggs", "eggs", 4],
    ["Töltött paprika", "peppers stuffed with pork and rice in tomato sauce", "bake", 4],
    ["Túrós csusza", "noodles with curd cheese, sour cream and bacon", "noodle", 5],
    ["Halászlé", "fisherman's paprika fish soup", "soup", 5],
    ["Rakott krumpli", "layered potatoes, eggs, sausage and sour cream", "bake", 5],
  ],
  Cajun: [
    ["Shrimp étouffée", "shrimp smothered in a blond roux sauce over rice", "braise", 4],
    ["Chicken and sausage gumbo", "dark-roux stew with chicken, andouille and okra", "soup", 4],
    ["Maque choux", "corn smothered with peppers and andouille", "veg", 4],
  ],
  Lowcountry: [
    ["Frogmore stew", "shrimp, sausage, corn and potatoes boiled with spice", "soup", 4],
    ["Hoppin' John", "black-eyed peas and rice with smoked pork", "grain", 4],
    ["Charleston red rice", "tomato rice with sausage", "grain", 4],
    ["Chicken perloo", "chicken and sausage rice pilau", "grain", 5],
  ],
  Appalachian: [
    ["Salmon cakes", "canned salmon patties with cornmeal", "sear", 4],
    ["Soup beans and cornbread", "pinto beans with smoked ham, with cornbread", "soup", 4],
    ["Kilt lettuce and beans", "greens wilted with hot bacon dressing, over soup beans", "veg", 5],
    ["Chicken and slicks", "chicken with rolled flat dumplings", "soup", 5],
  ],
  "Pacific Northwest": [
    ["Cedar-plank salmon", "salmon roasted on a cedar plank", "roast", 4],
    ["Dungeness crab rolls", "crab salad in toasted buns", "handheld", 4],
    ["Smoked salmon hash", "hot-smoked salmon and potatoes with eggs", "eggs", 4],
  ],
};

/* Entries as objects, for code. */
export const DISH_BANK = Object.fromEntries(Object.entries(B).map(([trad, rows]) =>
  [trad, rows.map(([name, gloss, format, tier]) => ({ name, gloss, format, tier, tradition: trad }))]));

/* Dishes that can't honestly be done in 45 minutes (long braises, shredded
   meat). Offered only when the person allows an hour or more: the creativity
   judge flagged ropa vieja and black pork curry against a 45-minute limit. */
export const SLOW_DISHES = new Set(["Ropa vieja", "Black pork curry", "Escondidinho", "Beef rendang", "Hong shao rou",
  "Hong shao rou, Mao style", "Carne adovada", "Carbonada", "Mojo pork", "Goulash", "Gołąbki", "Doro wat", "Fesenjan",
  "Posole", "Kharcho", "Carne de porco à alentejana", "Char siu", "Pastelón", "Bobotie", "Arroz carreteiro", "Thieboudienne", "Drunken chicken"]);

/* Which tiers a role draws from, best first. */
/* "regional" leans on the deep list too: measured, tier-4 dishes from the
   better-known cuisines (dakgalbi, gumbo) read as level 3 to a blind judge. */
export const ROLE_TIERS = { known: [3, 4], regional: [5, 4], deep: [5, 4] };
