/* Extra hand-placed 16×16 sprites for the Mise launch film (original). */
(function () {
  const G = PPM.defGrid, K = '#1c1717';

  G('board', [  // paddle cutting board, handle on the right with a hanging hole, grain streaks
    '................',
    '................',
    '................',
    'kkkkkkkkkkk.....',
    'kwWWwwwwwwkkkkk.',
    'kwwwwdddwwwwwwwk',
    'kwwwwwwwwwwwkwwk',
    'kwdddwwwwwwwwwwk',
    'kwwwwwwwwddwkkkk',
    'kwwwwwwwwwwk....',
    'kwwwddddwwwk....',
    'kkkkkkkkkkkk....',
    '................',
    '................',
    '................',
    '................'], { k: K, w: '#E2B57A', W: '#F4D3A0', d: '#B98549' });

  G('bowl', [
    '................',
    '................',
    '................',
    '................',
    '....gg..rr......',
    '...gGgrrRrr.....',
    '.kkkkkkkkkkkkkk.',
    'kwWwwwwwwwwwwwsk',
    'kwwwwwwwwwwwwwsk',
    '.kwwwwwwwwwwwsk.',
    '..kwwwwwwwwwsk..',
    '...kkwwwwwwkk...',
    '.....kkkkkk.....',
    '................',
    '................',
    '................'], { k: K, w: '#F2EEE6', W: '#FFFFFF', s: '#C9C1AE', g: '#57A845', G: '#77C45A', r: '#D9261C', R: '#FF7A66' });

  G('timer', [
    '.......kk.......',
    '......kRRk......',
    '.....kkkkkk.....',
    '...kkrrrrrrkk...',
    '..krrRrrrrrrrk..',
    '.krrwwwwwwwwrrk.',
    '.krwwwwkwwwwwrk.',
    'krrwwwwkwwwwwrrk',
    'krrwwwwkkkkwwrrk',
    'krrwwwwwwwwwwrrk',
    '.krwwwwwwwwwwrk.',
    '.krrwwwwwwwwrrk.',
    '..krrrrrrrrrdk..',
    '...kkddddddkk...',
    '.....kkkkkk.....',
    '................'], { k: K, r: '#D9261C', R: '#FF8A73', d: '#9C130E', w: '#F4F0E6' });

  G('salt', [
    '.....kkkkkk.....',
    '....kmmmmmmk....',
    '....kmhmhmmk....',
    '....kkkkkkkk....',
    '....kwwwwwwk....',
    '...kwWwwwwwsk...',
    '...kwwwwwwwsk...',
    '...kwwwwwwwsk...',
    '...kwwwwwwwsk...',
    '...kwwwwwwwsk...',
    '...kwwwwwwwsk...',
    '...kwwwwwwssk...',
    '...kkkkkkkkkk...',
    '................',
    '................',
    '................'], { k: K, m: '#9EA3AD', h: '#5E636B', w: '#F2EEE6', W: '#FFFFFF', s: '#C9C1AE' });

  G('recipe', [
    '................',
    '..kkkkkkkkkkk...',
    '..kwwwwwwwwwwk..',
    '..kwrrrrrwwwwk..',
    '..kwwwwwwwwwwk..',
    '..kwllllllllwk..',
    '..kwwwwwwwwwwk..',
    '..kwlllllllwwk..',
    '..kwwwwwwwwwwk..',
    '..kwllllllwwwk..',
    '..kwwwwwwwwwwk..',
    '..kwlllllllwwk..',
    '..kwwwwwwwwwsk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................'], { k: K, w: '#F6F1E4', r: '#D9261C', l: '#9C9488', s: '#D8CFBC' });

  // Brand sprites converted from the user's ChatGPT pixel art (assets/*-pixel.png) with tools/image-to-grid.py
  /* toque: 20x17 cells from toque-pixel.png (cell 41px) */
  PPM.defGrid('toque', [
    '......kkkkkkkk......',
    '.....kbbbbbbbbk.....',
    '....kbbbbbbbbbbk....',
    '..kkkbbbbbbbbbbkkk..',
    '.kbbabbbbbbbbbbkbbk.',
    'kbbbbbbbbbbbbbbabbbk',
    'kbbbbabbbbbbbbabbbbk',
    'kbbbbaabbbbbbaabbbbk',
    'kbbbbaabbbbbbaabbbbk',
    '.kbbbaaabbbbaaabbbk.',
    '..kbbaaabbbbaaabbk..',
    '...kbaaaaaaaaaabk...',
    '....bkkkkkkkkkkb....',
    '....abbbbbbbbbba....',
    '....abbaaaaaabba....',
    '....aaaaaaaaaaaa....',
    '....kkkkkkkkkkkk....',
  ], { k: '#241414', a: '#D4C4C4', b: '#F4ECE4' });

  /* mise: 22x38 cells from mise-pixel.png (cell 28px) */
  PPM.defGrid('mise', [
    '.......kkkkkkkk.......',
    '......kffffffffk......',
    '.....kffffffffffk.....',
    '..kkkkffffffffffkkkk..',
    '.kfffcffffffffffkfffk.',
    'kfffffffffffffffdffffk',
    'kfffffdffffffffdfffffk',
    'kfffffddffffffddfffffk',
    'kfffffbdffffffddfffffk',
    'kdffffbddffffdddfffffk',
    '.kdfffbddffffddcfffdk.',
    '..kkdfbddddddddcfdkk..',
    '...kdfkkkkkkkkkkfdk...',
    '...kkdffffffffffdkk...',
    '...kdffffffffffffdk...',
    '...kdfffddddddfffdk...',
    '...kdfkkkkkkkkkkfdk...',
    '...kdkffffffffffkdk...',
    '....kffffffffffffk....',
    '...kfffkffffffkfffk...',
    '...kfffkffffffkfffk...',
    '...kffffffffffffffk...',
    '....kffffkffkffffk....',
    '....kffffffkffffkk....',
    '.....kkffffffffkk.....',
    '......kkffffffkk......',
    '.....kaakkkkkkak......',
    '....kkaaakkkaaaak.....',
    '....ffkaaakkaaakfk....',
    '..kkfffkakkkkakffffk..',
    '.kfffffdkakkakdfffffk.',
    'kfffffffkaakakffffdffk',
    'kffffffffakkaffkekfffk',
    'kffffffffkffkffkkkdffk',
    'kffdffffffffffffffdffk',
    '.kfdfffkfffffkffffdfk.',
    '..kkdffffffffffffdkk..',
    '....kkkkkkkkkkkkkk....',
  ], { k: '#24140C', a: '#B4441C', b: '#948474', c: '#AC9C8C', d: '#D4C4BC', e: '#F4BCB4', f: '#F4ECE4' });

  window.MISE_SET = ['knife', 'board', 'bowl', 'garlic', 'lemon', 'tomato', 'egg', 'pan', 'spoon', 'salt', 'recipe', 'timer'];
})();
